### PR TITLE
merge from belledonne

### PR DESCRIPTION
**Pull request by shareefalis**

### CODE REVIEW

**Comment by shareefalis** [comment]
DO NOT MERGE!

**Comment by shareefalis** [comment]
+1 offical fix from belledonne

**Comment by ianblenke** [comment]
What Jira ticket # is this?

**Comment by ianblenke** [comment]
+1 LGTM

**Comment by shareefalis** [comment]
https://vtcsecure.atlassian.net/browse/VATRP-525 
 an official fix.

**Pull request merged**
