### PR TITLE
Linphone core upgrade

### PR DESCRIPTION
**Pull request by shareefalis**

### CODE REVIEW

**Comment by shareefalis** [comment]
https://github.com/VTCSecureLLC/ace-android/pull/335 depend on this being merged.

**Comment by patrickmwatson** [comment]
+1 LGTM

**Comment by patrickmwatson** [comment]
Waiting to confirm it builds since #335 has been merged, no more conflicts.

**Comment by patrickmwatson** [comment]
+1 Hooray!

**Pull request merged**
