### PR TITLE
VATRP-2746: Android/ User specific data for Patrick review

### PR DESCRIPTION
**Pull request by Semrubo**
Call History and Chat history will be stored separately for separate users(logins).

### CODE REVIEW

**Comment by shareefalis** [comment]
-1 fix the diff of linphoneactivity.java i can't see what changed.

**Comment by patrickmwatson** [comment]
Also has conflicts :(

**Comment by kennethdick** [comment]
careful on this one. it is not required for GA, there are a lot of moving pieces here

**Comment by patrickmwatson** [comment]
Not merging until after GA for safety, since it is not a contractual requirement.

**Pull request closed without merging**
