### PR TITLE
merge from belledonne

### PR DESCRIPTION
**Pull request by shareefalis**

### CODE REVIEW

**Comment by shareefalis** [comment]
@ianblenke you will need to update linphone submodule

**Comment by ianblenke** [comment]
Merge conflicts. Need to fix those first.

**Comment by ianblenke** [comment]
Ah, correction, travis-ci build failure... not merge conflicts.

**Comment by ianblenke** [comment]
Oh, right, I need to update the linphone repo first. Like you said. Sorry, I'm still slurping coffee over here trying to wake up!

**Comment by shareefalis** [comment]
I just fast forwarded the linphone submodule. So now you don't don't need to worry about it now.

**Pull request merged**
